[package]
name = "crypto-learning"
version = "0.1.0"
authors = ["ikanago <ikanago@ikanago.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.0"
rand = "0.8.3"
